# Generated by Django 4.2.7 on 2023-12-03 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor_access', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorAccess',
            new_name='VisitorAccessRequest',
        ),
        migrations.AlterModelOptions(
            name='visitoraccessrequest',
            options={'verbose_name_plural': 'Visitor Access Request'},
        ),
        migrations.RenameField(
            model_name='visitoraccessrequest',
            old_name='ticket_number',
            new_name='request_number',
        ),
        migrations.RenameField(
            model_name='visitoraccessrequest',
            old_name='ticket_status',
            new_name='request_status',
        ),
    ]
