# Generated by Django 4.2.7 on 2024-05-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_access', '0002_rename_visitoraccess_visitoraccessrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoraccessrequest',
            name='access_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
