# Generated by Django 4.2.7 on 2024-05-03 13:12

from django.db import migrations, models
import visitor_access.models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_access', '0003_visitoraccessrequest_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitoraccessrequest',
            name='request_number',
        ),
        migrations.AlterField(
            model_name='visitoraccessrequest',
            name='access_code',
            field=models.CharField(default=visitor_access.models.generate_access_code, max_length=5, unique=True),
        ),
    ]
