# Generated by Django 4.2.7 on 2024-03-15 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_bill', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('bin_collection', 'Bin Collection')], default='Choose bill type', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_creditor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dwell Dues',
                'ordering': ['-payment_date'],
            },
        ),
    ]
