# Generated by Django 4.2.7 on 2024-03-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwell_dues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='00', max_digits=10),
        ),
    ]
