# Generated by Django 4.2.7 on 2024-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwell_dues', '0004_alter_dues_utility_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dues',
            name='utility_bill',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('bin_collection', 'Bin Collection')], default='---', max_length=20),
        ),
    ]
