# Generated by Django 4.2.7 on 2024-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwell_dues', '0006_alter_dues_utility_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dues',
            name='utility_bill',
            field=models.CharField(choices=[('', 'Select utility type'), ('electricity', 'Electricity'), ('water', 'Water'), ('bin collection', 'Bin Collection')], max_length=20),
        ),
    ]
