# Generated by Django 4.2.7 on 2023-12-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_mail', '0002_conversation_conversationmessage_delete_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
