# Generated by Django 4.2.7 on 2023-12-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_mail', '0003_alter_conversation_options_conversation_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='subject',
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
