# Generated by Django 4.2.7 on 2023-12-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_mail', '0004_remove_conversation_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ReplyMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('date_replied', models.DateTimeField(auto_now_add=True)),
                ('new_content', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='new_mail_content', to='community_mail.newmail')),
                ('new_subject', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='new_mail_subject', to='community_mail.newmail')),
            ],
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
