# Generated by Django 4.2.7 on 2023-12-08 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_mail', '0005_newmail_replymail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newmail',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'New Mail'},
        ),
        migrations.AddField(
            model_name='newmail',
            name='sent_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replymail',
            name='reply_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
