# Generated by Django 4.2.7 on 2023-12-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_mail', '0006_alter_newmail_options_newmail_sent_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replymail',
            old_name='reply',
            new_name='reply_message',
        ),
    ]
