# Generated by Django 4.2.7 on 2024-03-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critical_alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticalalert',
            options={'ordering': ['-date_sent'], 'verbose_name_plural': 'Critical Alert'},
        ),
        migrations.RenameField(
            model_name='criticalalert',
            old_name='send_alert',
            new_name='alert',
        ),
    ]
