# Generated by Django 4.2.7 on 2024-03-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('critical_alert', '0002_alter_criticalalert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalalert',
            name='receiver',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, related_name='alert_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
