# Generated by Django 4.2.7 on 2024-03-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critical_alert', '0004_alter_criticalalert_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalalert',
            name='receiver',
        ),
    ]
