# Generated by Django 4.2.7 on 2024-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critical_alert', '0007_remove_criticalalert_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticalalert',
            name='alert',
            field=models.TextField(default='Please Help!!!'),
        ),
    ]
