# Generated by Django 4.2.7 on 2023-12-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catgeory',
            new_name='category',
        ),
    ]
