# Generated by Django 4.2.7 on 2024-03-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_house_number_user_street_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_name',
            field=models.CharField(max_length=100),
        ),
    ]
