# Generated by Django 4.2.7 on 2024-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_allstreets_housenumbers_alter_user_house_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allstreets",
            options={"verbose_name_plural": "All Streets"},
        ),
        migrations.AlterModelOptions(
            name="housenumbers",
            options={"verbose_name_plural": "House Numbers"},
        ),
        migrations.AddField(
            model_name="user",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
